//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2021. 05. 05. 23:14:28
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace PhoneBook
{
    public partial class Login {

        public Login()
        {
            OnCreated();
        }

        public virtual short Id { get; set; }

        public virtual string Username { get; set; }

        public virtual string Password { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
